### ISSUE TITLE
Typos on Homepage

### ISSUE THREAD

**Issue by samuelswinslow** [aionnetwork/aion_explorer#10]
LOVE the dashboard/explorer! Here's just a few little typos I've stumbled across:
"Latest" and "Difficulty"
<img width="401" alt="screen shot 2018-03-06 at 4 52 07 pm" src="https://user-images.githubusercontent.com/22669858/37112131-9d1a510e-220f-11e8-9fcb-a02a4edea5c8.png">
<img width="420" alt="screen shot 2018-03-06 at 4 52 18 pm" src="https://user-images.githubusercontent.com/22669858/37112133-9d33835e-220f-11e8-9d0b-46b824032f5f.png">

Unsure of how bounty works-- if there's one for this-- 0xc338eddDc7C624e9BD2B6162fb7ecda904A81ce1 thanks! :)

**Comment by ali-sharif** [comment]
updated.
