### ISSUE TITLE
Account gone / reset

### ISSUE THREAD

**Issue by JimVanEeden** [aionnetwork/aion_explorer#11]
I'm not sure whether this is a dashboard issue or something else, so if not I can repost the issue in the appropriate repo.

My kernel version 0.1.14 was mining for about a week when it branched off of the main chain somewhere during the weekend. Just now I upgraded to 0.1.15 and noticed my account was missing from the dashboard. As there were some issues with 0.1.15 I reverted back to 0.1.14, resynced from block 300000. My account came back on the dashboard after that.

However, the number of blocks mined was totally reset. The dashboard showed 0 (it has increased since then). Before I had more than 300 blocks mined on that account.

**Comment by ali-sharif** [comment]
Let me debug this. It is probably just a dashboard data caching issue on the server-side, as under very variable network conditions which exist on the testnet as we deploy new code, the dashboard is constantly trying to track what it believes to be the main-chain and reorganizing at the tips as it sees temporary sidechains.
