### ISSUE TITLE
the number of mined blocks is not correct? 

### ISSUE THREAD

**Issue by Xiaoyang-Zhu** [aionnetwork/aion_explorer#13]
why the number of mined blocks shown in dashboard is not correct?

like this one

https://dashboard.aion.network/#/account/5d9171b3bae46c03df09abe57c194d58804e06aa2a6f92a9d834b133527e985b5

discussion is here:
https://forum.aion.network/t/why-the-number-of-mined-blocks-is-not-correct/473

**Comment by ali-sharif** [comment]
@Xiaoyang-Zhu - This fix is gonna be batched into updates that we're planning for this weekend to the dashboard. Seems to be a data consistency issue with the off-kernel chain replica the dashboard keeps for querying.
