### ISSUE TITLE
Api calls on wiki outdated

### ISSUE THREAD

**Issue by Glyck** [aionnetwork/aion_explorer#22]
The api query commands on the wiki are outdated or only works on the testnet-1. 
https://github.com/aionnetwork/aion_explorer/wiki/Explorer-Data-API

**Comment by ali-sharif** [comment]
Yessir. Since we don't plan to maintain that api publically (notice was provided on the wiki that previously documented that API), I have taken down that documentation. 

Hopefully someone from the community in the near future can run an Aion API for the public to consume.
