### ISSUE TITLE
First/Latest transaction on account displays incorrectly without transactions

### ISSUE THREAD

**Issue by JimVanEeden** [aionnetwork/aion_explorer#9]
![screenshot from 2018-03-07 14-38-12](https://user-images.githubusercontent.com/5991446/37095110-47fb03fc-2215-11e8-9459-e182a4e35552.png)

Without any transactions it seems to just take the 1 unix timestamp instead of something to indicate that there were no transactions.

**Comment by aion82** [comment]
ya sure

**Comment by ali-sharif** [comment]
Thanks for reporting this. Will be patched on next round of updates later this week.
